In [2]:
import pandas as pd
import sklearn as sk
import os
import numpy as np
from sklearn import linear_model
from sklearn.linear_model import LinearRegression

In [3]:
game_results = pd.read_csv("../data/clean/game_results_clean.csv", encoding="ISO-8859-1")

In [4]:
game_results.head()
## fills the single missing rpi with the mean of the all the rpis
mean_value=game_results['team2_rpi'].mean()
game_results['team2_rpi'].fillna(value=game_results['team2_rpi'].mean(), inplace=True)

In [5]:
game_results['team2_rpi'].isnull().sum()

0

In [6]:
x = game_results[['team1_osrs','team1_dsrs','team1_rpi','team2_osrs','team2_dsrs','team2_rpi']]
y = game_results['score_diff']

In [7]:
regr = LinearRegression(fit_intercept=False).fit(x,y)
print('Intercept: \n', regr.intercept_)
print('Coefficients: \n', regr.coef_)

Intercept:
 0.0
Coefficients:
 [  1.02808354   1.11286337 -30.53191958  -0.96870805  -1.07654445
  29.23121343]

In [8]:
game_results.head()

,year,round,team1,team2,score1,score2,score_diff,seed1,seed2,seed_diff,team1_sos,team1_osrs,team1_dsrs,team1_srs,team1_rpi,team2_sos,team2_osrs,team2_dsrs,team2_srs,team2_rpi
0,2019,National Championship,Virginia,Texas Tech,85,77,8,1,3,-2,10.15,5.08,20.38,25.46,0.6554,9.53,5.95,16.84,22.79,0.6187
1,2019,Final Four,Michigan State,Texas Tech,51,61,-10,2,3,-1,12.34,12.94,11.99,24.93,0.6468,9.53,5.95,16.84,22.79,0.6187
2,2019,Final Four,Virginia,Auburn,63,62,1,1,4,-3,10.15,5.08,20.38,25.46,0.6554,10.92,13.12,7.72,20.84,0.6187
3,2019,Elite Eight,Virginia,Purdue,80,75,5,1,3,-2,10.15,5.08,20.38,25.46,0.6554,11.99,12.29,9.11,21.40,0.6199
4,2019,Elite Eight,Gonzaga,Texas Tech,69,75,-6,1,3,-2,5.01,18.57,9.22,27.79,0.6443,9.53,5.95,16.84,22.79,0.6187

In [9]:
game_results['team1_rating'] = (game_results['team1_osrs']*1.02808354)+(game_results['team1_dsrs']*1.11286337)+(game_results['team1_rpi']*-30.53191958)
game_results['team2_rating'] = (game_results['team2_osrs']*-0.96870805)+(game_results['team2_dsrs']*-1.07654445)+(game_results['team2_rpi']*29.23121343)

In [10]:
game_results.head()

,year,round,team1,team2,score1,score2,score_diff,seed1,seed2,seed_diff,...,team1_dsrs,team1_srs,team1_rpi,team2_sos,team2_osrs,team2_dsrs,team2_srs,team2_rpi,team1_rating,team2_rating
0,2019,National Championship,Virginia,Texas Tech,85,77,8,1,3,-2,...,20.38,25.46,0.6554,9.53,5.95,16.84,22.79,0.6187,7.892200,-5.807470
1,2019,Final Four,Michigan State,Texas Tech,51,61,-10,2,3,-1,...,11.99,24.93,0.6468,9.53,5.95,16.84,22.79,0.6187,6.898587,-5.807470
2,2019,Final Four,Virginia,Auburn,63,62,1,1,4,-3,...,20.38,25.46,0.6554,10.92,13.12,7.72,20.84,0.6187,7.892200,-2.935021
3,2019,Elite Eight,Virginia,Purdue,80,75,5,1,3,-2,...,20.38,25.46,0.6554,11.99,12.29,9.11,21.40,0.6199,7.892200,-3.592313
4,2019,Elite Eight,Gonzaga,Texas Tech,69,75,-6,1,3,-2,...,9.22,27.79,0.6443,9.53,5.95,16.84,22.79,0.6187,9.680396,-5.807470

In [11]:
game_results.to_csv(os.path.join("..","data", "clean", "game_results_clean.csv"), index = False)